import React from "react";
import ProvidersClientWrapper from "@/app/services/wagmi/client__provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import setting from "@/app/config/conf/setting.json"; 
import { Header, Footer } from "@/app/components";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  alternates: {
    canonical: setting.domain__links,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: setting.domain__links,
    siteName: "Cordy Developments",
    images: [
      {
        url: setting.openGraph,
        width: 800,
        height: 600,
      },
      {
        url: setting.openGraph,
        width: 1800,
        height: 1600,
        alt: "Cordy Portfolio",
      },
    ],
    locale: "en-US",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ProvidersClientWrapper>
        <Header />
        {children}
        <Footer />
        </ProvidersClientWrapper>
      </body>
    </html>
  );
}
